"""foam_concrete_case 剧本：转录竞赛文档 §7.1–7.3。全部为合成演示数据（cycles v2，意见/处置分离）。"""
from app.scenario.schema import (
    Decision,
    DiscriminatingExperiment,
    Disposition,
    DiscussionSession,
    DiscussionTurn,
    ExperimentResults,
    FinalState,
    HypothesisUpdate,
    Master,
    MasterClaim,
    Meeting,
    MeetingCycle,
    PostdocExchange,
    PreviewQuestion,
    ReviewGate,
    ReviewItem,
    Scenario,
)

FOAM_CONCRETE_SCENARIO = Scenario(
    package_id="foam_concrete_case",
    cycles=[
        MeetingCycle(
            cycle=1,
            scheduled_for="第 1 周组会",
            masters=[
                Master(agent_id="agent-ms-1", capability="文献与机制分析",
                       claim=MasterClaim(
                           statement="在含水修正、目标湿密度和发泡工艺可比条件下，泥浆条件先改变新拌体系与气泡稳定表现，继而改变孔结构，并可能伴随强度变化。",
                           evidence_refs=["lit-1"],
                           boundary="仅适用于含泡新拌体系，且需同批可对应样品。",
                           prediction="含泡样品中气泡稳定与孔结构随泥浆条件出现可重复变化。",
                           falsification_condition="含泡样品中气泡稳定或孔结构没有随泥浆条件出现可重复变化。")),
                Master(agent_id="agent-ms-2", capability="实验与测试方法",
                       claim=MasterClaim(
                           statement="当前首先需要核查湿密度与实验控制条件，在工艺变量可比之前不能排除“假象”。",
                           evidence_refs=["anomaly-1"],
                           boundary="适用于工艺变量尚未可比的情形；核查完成前不宜下机制结论。",
                           prediction="核查后差异仍然存在，且与气泡/孔结构变化对应。",
                           falsification_condition="核查后差异消失，或差异与气泡/孔结构变化不对应。")),
                Master(agent_id="agent-ms-3", capability="数据与证据分析",
                       claim=MasterClaim(
                           statement="现有数据的样品链、批次和测试对应关系不完整，暂不足以支持任何机制判断。",
                           evidence_refs=["anomaly-1"],
                           boundary="适用于当前样品对应关系不完整的阶段。",
                           prediction="补齐样品对应后，差异模式仍然稳定。",
                           falsification_condition="补齐样品对应后，差异模式不稳定或无法建立对应关系。")),
            ],
            discussion_sessions=[
                DiscussionSession(
                    session_id="ds-1", kind="collaborative",
                    initiator="agent-ms-1", trigger="uncertain_claim",
                    participants=["agent-ms-1", "agent-ms-2", "agent-ms-3"],
                    turns=[
                        DiscussionTurn(speaker="agent-ms-1", kind="collaborate",
                                       content="我对‘含泡体系气泡稳定的可重复性’把握不足，需要含泡样品的新拌稳定表现证据。"),
                        DiscussionTurn(speaker="agent-ms-2", kind="collaborate",
                                       content="可先核查湿密度与实验控制条件，把‘假象’排除后再讨论机制差异。"),
                        DiscussionTurn(speaker="agent-ms-3", kind="collaborate",
                                       content="我这边难找到能一一对应的样品链，建议先建立样品对应规则再比较。"),
                        DiscussionTurn(speaker="agent-ms-1", kind="collaborate",
                                       content="好，先补齐样品链，再讨论气泡稳定路径。"),
                    ]),
            ],
            postdoc_exchange=[
                PostdocExchange(requester="agent-ms-2", speaker="agent-ms-2", kind="request",
                                content="在已声明的孔结构与含泡体系测量范围内，哪些观测组合能够把“无泡浆体代理”与“含泡样品证据”区分开？"),
                PostdocExchange(speaker="agent-postdoc-1", kind="in_scope_answer",
                                content="响应契约示意：在已声明的孔结构与含泡体系测量范围内，含泡新拌稳定表现与孔结构的配对观测组合可能具有判别价值；正式领域回答只有在接入真实知识库并核验来源后才能形成，且必须返回知识库版本、检索来源、适用条件、不确定性与限制，不替任何一方下结论。",
                                sources=["kb-v0"]),
                PostdocExchange(requester="agent-phd-1", speaker="agent-phd-1", kind="request",
                                content="特定早期反应或固相结构是否必然主导强度？"),
                PostdocExchange(speaker="agent-postdoc-1", kind="out_of_scope_refusal",
                                content="该问题超出当前已声明的专业与知识库覆盖范围，无法依据本领域知识库作答。"),
            ],
            review_gate=ReviewGate(reviewer="agent-phd-1", items=[
                ReviewItem(kind="counterexample",
                           content="无泡流变数据不能直接迁移到含泡体系。"),
                ReviewItem(kind="falsification_condition",
                           content="控制新拌差异后强度差异是否仍保留？"),
                ReviewItem(kind="missing_observation",
                           content="强度、孔结构与反应表征的样品对应关系缺失。"),
            ]),
            review_triggered_sessions=[
                DiscussionSession(
                    session_id="ds-2", kind="adversarial",
                    initiator="agent-phd-1", trigger="review_conflict",
                    participants=["agent-ms-1", "agent-ms-2", "agent-ms-3", "agent-phd-1"],
                    turns=[
                        DiscussionTurn(speaker="agent-ms-1", kind="proposal", seat="proposal_owner",
                                       content="围绕含泡新拌体系设计可对应的观测与判别实验。"),
                        DiscussionTurn(speaker="agent-ms-2", kind="attack", seat="discriminability",
                                       content="现有流变记录若仅来自无泡浆体，为什么可以迁移到含泡体系？这种观察又如何排除有效水胶比或目标湿密度偏离造成的假象？"),
                        DiscussionTurn(speaker="agent-ms-3", kind="attack", seat="feasibility_evidence",
                                       content="当前数据存在批次/样品对应问题，方案必须先锁定样品链，否则均值比较无法补回缺失的配对关系。"),
                        DiscussionTurn(speaker="agent-ms-1", kind="revision", seat="proposal_owner",
                                       content="方案修订为：只有完成含水修正、目标湿密度核查和同配方发泡步骤，并在同批、可对应的含泡样品上同时观察到新拌稳定表现和孔结构变化时，才讨论该路径。"),
                        DiscussionTurn(speaker="agent-ms-2", kind="proposal", seat="proposal_owner",
                                       content="先做一组受控对比实验，在固定湿密度与工艺条件下比较不同泥浆掺量。"),
                        DiscussionTurn(speaker="agent-ms-3", kind="attack", seat="discriminability",
                                       content="该设计能否区分“机制差异”与“样品差异”？"),
                        DiscussionTurn(speaker="agent-ms-1", kind="attack", seat="feasibility_evidence",
                                       content="新拌指标与强度、孔结构是否来自同一试件或预先声明的配对试件？"),
                        DiscussionTurn(speaker="agent-ms-2", kind="revision", seat="proposal_owner",
                                       content="主张修订为：缺失的样品链、湿密度、测试批次或异常记录先登记为证据缺口；只有后续配对样品在控制新拌条件后仍显示差异，B 的判断才值得继续检验。"),
                        DiscussionTurn(speaker="agent-ms-3", kind="proposal", seat="proposal_owner",
                                       content="先补齐样品对应规则与统计判定阈值，再做机制比较。"),
                        DiscussionTurn(speaker="agent-ms-1", kind="attack", seat="discriminability",
                                       content="补齐样品链后，哪些观测组合能把“无泡浆体代理”与“含泡样品证据”区分开？"),
                        DiscussionTurn(speaker="agent-ms-2", kind="attack", seat="feasibility_evidence",
                                       content="设备与试件数量是否支持完整测量集合？"),
                        DiscussionTurn(speaker="agent-ms-3", kind="revision", seat="proposal_owner",
                                       content="方案细化为：先建立样品对应规则，再按可判别分支设计测量集合。"),
                        DiscussionTurn(speaker="agent-phd-1", kind="proposal", seat="proposal_owner",
                                       content="当前关键缺口不是笼统的“缺少数据”，而是缺少能一一对应的含泡新拌观测、孔结构、强度与必要反应/固相表征，以及在预先控制混杂因素后如何解释它们的规则。"),
                        DiscussionTurn(speaker="agent-ms-3", kind="response",
                                       content="三方共同将该缺口转为最小判别实验：选择少量代表性泥浆条件，同步记录新拌浆体指标、含泡体系稳定表现，并对预先定义的对应试件进行强度和孔结构测试。"),
                        DiscussionTurn(speaker="agent-phd-1", kind="revision",
                                       content="博士后在结束讨论参与后切换为独立审核，检查方案的样品链、条件和判别力；领域回答、独立审核记录、阶段建议和导师批准分别保存，彼此不等价。"),
                    ]),
            ],
            dispositions=[
                Disposition(kind="counterexample",
                            content="无泡流变数据不能直接迁移到含泡体系。",
                            actor="agent-ms-1", disposition="accepted",
                            reason="现有流变记录仅来自无泡浆体，迁移不成立。"),
                Disposition(kind="falsification_condition",
                            content="控制新拌差异后强度差异是否仍保留？",
                            actor="agent-ms-2", disposition="accepted",
                            reason="作为可推翻条件登记为未决分歧。"),
                Disposition(kind="missing_observation",
                            content="强度、孔结构与反应表征的样品对应关系缺失。",
                            actor="agent-ms-3", disposition="accepted",
                            reason="需补齐同批对应样品。"),
            ],
            meeting=Meeting(
                agenda=["上周期行动项完成情况", "当前研究进展", "新增实验与数据", "下一周期计划"],
                unresolved_disagreements=["控制新拌差异后强度差异是否仍保留（未决）"],
                suggested_decision=Decision(actor="PI", option="returned",
                                            reason="证据不足：缺少能一一对应的含泡新拌观测与配对样品，需先补齐样品链与湿密度核查。"),
                action_items=["补齐样品对应规则", "锁定必要测量集合与判定顺序"],
            ),
        ),
        MeetingCycle(
            cycle=2,
            scheduled_for="第 2 周组会",
            masters=[
                Master(agent_id="agent-ms-1", capability="文献与机制分析",
                       claim=MasterClaim(
                           statement="放弃‘泥浆单独决定强度’，只保留‘新拌与气泡稳定是待比较的中间路径’。",
                           evidence_refs=["lit-1"],
                           boundary="仅在含泡新拌体系可对应观测时成立。",
                           prediction="含泡样品新拌稳定与孔结构配对观测显示可重复变化。",
                           falsification_condition="配对观测未显示可重复变化，或差异由工艺假象解释。")),
                Master(agent_id="agent-ms-2", capability="实验与测试方法",
                       claim=MasterClaim(
                           statement="保留‘先核查湿密度与实验控制’，机制判断推迟到样品链补齐之后。",
                           evidence_refs=["anomaly-1"],
                           boundary="样品链未补齐前不下机制结论。",
                           prediction="补齐配对样品并控制新拌后，差异模式仍稳定。",
                           falsification_condition="控制新拌后差异消失，或样品对应无法建立。")),
                Master(agent_id="agent-ms-3", capability="数据与证据分析",
                       claim=MasterClaim(
                           statement="维持‘当前数据不足以支持机制判断’，若补齐样品对应后差异稳定则重新开放。",
                           evidence_refs=["anomaly-1"],
                           boundary="当前阶段不排除任何机制，也不支持任何机制。",
                           prediction="补齐样品对应后差异模式稳定，需要重新开放判断。",
                           falsification_condition="补齐后差异模式不稳定或无法建立对应。")),
            ],
            discussion_sessions=[
                DiscussionSession(
                    session_id="ds-3", kind="collaborative",
                    initiator="agent-ms-3", trigger="hard_evidence",
                    participants=["agent-ms-1", "agent-ms-2", "agent-ms-3"],
                    turns=[
                        DiscussionTurn(speaker="agent-ms-3", kind="collaborate",
                                       content="退回理由是证据不足，我建议先锁定样品对应规则与统计判定阈值。"),
                        DiscussionTurn(speaker="agent-ms-2", kind="collaborate",
                                       content="可补一组受控对比实验，固定湿密度与工艺条件比较不同泥浆掺量。"),
                        DiscussionTurn(speaker="agent-ms-1", kind="collaborate",
                                       content="补含泡样品的新拌稳定与孔结构配对观测，才能检验‘新拌—孔结构’路径。"),
                        DiscussionTurn(speaker="agent-ms-3", kind="collaborate",
                                       content="好，样品链 + 配对观测 + 受控对比，三者合并作为判别实验的测量集合。"),
                    ]),
            ],
            postdoc_exchange=[],
            review_gate=ReviewGate(reviewer="agent-phd-1", items=[
                ReviewItem(kind="counterexample",
                           content="配对样品证据仍缺失：新拌、孔结构、强度尚未来自同一试件。"),
                ReviewItem(kind="falsification_condition",
                           content="若配对样品在控制新拌后差异消失，则机制路径不成立。"),
                ReviewItem(kind="missing_observation",
                           content="缺少预先锁定的效应阈值与判定顺序。"),
            ]),
            review_triggered_sessions=[],
            dispositions=[
                Disposition(kind="counterexample",
                            content="配对样品证据仍缺失：新拌、孔结构、强度尚未来自同一试件。",
                            actor="agent-ms-3", disposition="accepted",
                            reason="须补齐同批配对样品后再进入判别实验。"),
                Disposition(kind="falsification_condition",
                            content="若配对样品在控制新拌后差异消失，则机制路径不成立。",
                            actor="agent-ms-1", disposition="accepted",
                            reason="作为可推翻条件写入冻结方案。"),
                Disposition(kind="missing_observation",
                            content="缺少预先锁定的效应阈值与判定顺序。",
                            actor="agent-ms-2", disposition="accepted",
                            reason="效应阈值须依据设备精度与预实验锁定。"),
            ],
            meeting=Meeting(
                agenda=["上周期行动项完成情况", "补齐后的证据与对照", "判别实验方案", "下一周期计划"],
                unresolved_disagreements=["控制新拌差异后强度差异是否仍保留（已转为判别分支）"],
                suggested_decision=Decision(actor="PI", option="approved_with_conditions",
                                            reason="补齐样品链与湿密度核查、锁定测量集合与效应阈值后，投入最小判别实验。"),
                action_items=["锁定必要测量集合", "预注册结果模式与判定顺序"],
            ),
        ),
    ],
    discriminating_experiment=DiscriminatingExperiment(
        controls=["泥浆掺量", "含水修正", "目标湿密度", "发泡工艺", "养护制度"],
        sample_chain="新拌、含泡、孔结构、强度及必要表征须来自同一试件或预先声明的配对试件；无法满足对应规则的数据只标记为线索，不进入分支比较。",
        measurements=["新拌浆体指标", "含泡体系稳定表现", "孔结构", "抗压强度"],
        branches=["新拌—孔结构路径占主导", "工艺控制假象", "数据对应不足导致不可判别", "多路径共同作用"],
        candidate_explanations=[
            "泥浆条件先改变新拌体系与气泡稳定，继而影响孔结构与强度。",
            "强度与孔结构差异主要来自湿密度、含水修正或发泡工艺控制偏差。",
            "现有样品链不足，差异只能作为线索而不能进入机制比较。",
            "新拌稳定、孔结构与早期反应/固相结构可能共同作用。",
        ],
        branch_effects=[
            "上调新拌—孔结构路径的支持程度，但仍需独立验证机制。",
            "削弱机制解释，优先登记为工艺控制假象。",
            "保持不可判别状态，要求补齐同批配对样品后再判断。",
            "标记为后验候选解释，不倒写为预注册结论。",
        ],
        cost_risk="按真实可用设备与试件数量确定；AI 不执行真实实验，导师决定是否投入。",
    ),
    experiment_results=ExperimentResults(
        source="demo_csv",
        rows=[{"condition": "高泥浆掺量", "strength_mpa": 3.2, "macro_pore_ratio": 0.41,
               "sample_id": "demo-A1", "notes": "合成演示结果"}],
        notes="合成演示结果，非真实实验；结果须先核查样品、条件、原始数据、执行者和异常，再与预注册预测比较。",
        validation_summary="synthetic demo：样品、条件、方法与异常核查仅为演示摘要；真实实验需核验原始记录、执行者、设备与批次。",
    ),
    hypothesis_updates=[
        HypothesisUpdate(claim_id="agent-ms-1", status="supported",
                         reason="符合预测仅调整支持程度，不自动证明因果机制。"),
        HypothesisUpdate(claim_id="agent-ms-2", status="inconclusive",
                         reason="湿密度核查路径仍待配对样品独立验证。"),
        HypothesisUpdate(claim_id="agent-ms-3", status="inconclusive",
                         reason="样品对应补齐后差异模式仍待独立验证。"),
    ],
    final_state=FinalState(
        summary="泥浆条件可能先改变新拌体系与气泡稳定，并在特定材料与工艺条件下再与早期反应/固相结构共同影响孔结构与强度；相关性不等于因果。",
        mechanism_draft="泥浆掺量升高 → 新拌体系/气泡稳定变化 → 孔结构改变 → 强度变化（演示候选假设，待独立验证；后验解释不得倒写为预注册结论）。",
    ),
    preview_questions=[
        PreviewQuestion(question_id="pq-1",
                        question="控制新拌差异后，强度差异是否仍保留？",
                        hint="未决分歧：需要配对样品证据"),
        PreviewQuestion(question_id="pq-2",
                        question="无泡浆体的流变数据能否直接迁移到含泡体系？",
                        hint="审查门反例：缺少含泡体系流变数据"),
        PreviewQuestion(question_id="pq-3",
                        question="强度、孔结构与反应表征是否来自同一试件或配对试件？",
                        hint="样品对应规则：数据对应不足只能标记为线索"),
        PreviewQuestion(question_id="pq-4",
                        question="若所有判别分支都未达到效应阈值，你会如何判定？",
                        hint="预注册判定：记录“未检验/不可判别”而非强行下结论"),
    ],
)
